### ISSUE TITLE
XFCE compilation error for xfce4-panel-4.14.3

### ISSUE THREAD

**Issue by robertwolter** [ataraxialinux/ataraxia#107]
---
title: 'Bug Report xfce4-panel-4.14.3 '
labels: bug xfce4-panel-4.14.3
  ---

# Package Bug:
xfce4-panel-4.14.3
## Expected Behavior
Compilation success

## Actual Behavior
Compilation failed

## Steps to Reproduce the Problem

  1.
neko emerge xfce
## Specifications

  - Architecture: x64_86
  - Package Version: 4.14.3

Other Notes:

Excerpt from log:
neko emerge xfce
[...]
make  all-recursive
make[1]: Entering directory '/usr/ports/packages/xfce4-panel/work/src/xfce4-panel-4.14.3'
Making all in libxfce4panel
make[2]: Entering directory '/usr/ports/packages/xfce4-panel/work/src/xfce4-panel-4.14.3/libxfce4panel'
make  all-am
make[3]: Entering directory '/usr/ports/packages/xfce4-panel/work/src/xfce4-panel-4.14.3/libxfce4panel'

[...]

/usr/include/glib-2.0/glib/gtypes.h:547:8: note: declared here
  547 | struct _GTimeVal
      |        ^~~~~~~~~
  CCLD     libxfce4panel-1.0.la
  GISCAN   libxfce4panel-2.0.gir
xfce-panel-macros-46.h:55: Warning: libxfce4panel: symbol='panel_slice_alloc': Unknown namespace for symbol 'panel_slice_alloc'
xfce-panel-macros-46.h:68: Warning: libxfce4panel: symbol='panel_slice_alloc0': Unknown namespace for symbol 'panel_slice_alloc0'
xfce-panel-macros-46.h:80: Warning: libxfce4panel: symbol='panel_slice_free1': Unknown namespace for symbol 'panel_slice_free1'
xfce-panel-macros-46.h:93: Warning: libxfce4panel: symbol='panel_slice_new': Unknown namespace for symbol 'panel_slice_new'
xfce-panel-macros-46.h:106: Warning: libxfce4panel: symbol='panel_slice_new0': Unknown namespace for symbol 'panel_slice_new0'
xfce-panel-macros-46.h:118: Warning: libxfce4panel: symbol='panel_slice_free': Unknown namespace for symbol 'panel_slice_free'
xfce-panel-macros-46.h:131: Warning: libxfce4panel: symbol='PANEL_PARAM_READABLE': Unknown namespace for symbol 'PANEL_PARAM_READABLE'
xfce-panel-macros-46.h:142: Warning: libxfce4panel: symbol='PANEL_PARAM_WRITABLE': Unknown namespace for symbol 'PANEL_PARAM_WRITABLE'
xfce-panel-macros-46.h:153: Warning: libxfce4panel: symbol='PANEL_PARAM_READWRITE': Unknown namespace for symbol 'PANEL_PARAM_READWRITE'
  GICOMP   libxfce4panel-2.0.gir
 VAPIGEN libxfce4panel-2.0.vapi
warning: empty metadata
libxfce4panel-2.0.gir:2359.7-2359.40: error: overriding method `Xfce.PanelPlugin.remote_event' is incompatible with base method `bool Xfce.PanelPluginProvider.remote_event (string, GLib.Value, uint)': too few parameters.
make[3]: *** [/usr/share/vala/Makefile.vapigen:61: libxfce4panel-2.0.vapi] Error 1
make[3]: Leaving directory '/usr/ports/packages/xfce4-panel/work/src/xfce4-panel-4.14.3/libxfce4panel'
make[2]: *** [Makefile:891: all] Error 2
make[2]: Leaving directory '/usr/ports/packages/xfce4-panel/work/src/xfce4-panel-4.14.3/libxfce4panel'
make[1]: *** [Makefile:612: all-recursive] Error 1
make[1]: Leaving directory '/usr/ports/packages/xfce4-panel/work/src/xfce4-panel-4.14.3'
make: *** [Makefile:523: all] Error 2
:: Failed to compile package: xfce4-panel

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/23b689adb69f8eac7b714cda2354460625a6f053 hope this fixes. Test!

**Comment by robertwolter** [comment]
Thanks, that fixed it.
