### ISSUE TITLE
 ERROR: Dependency "libsystemd" not found

### ISSUE THREAD

**Issue by robertwolter** [ataraxialinux/ataraxia#109]
---
title: 'Bug Report, libsystemd not found'
labels: bug libsystemd 
  ---

# Package Bug: 
vte-0.60.0

## Expected Behavior
Compilation success

## Actual Behavior
Compilation failed

## Steps to Reproduce the Problem

  1.
neko emerge xfce
## Specifications

  - Architecture: x64_86
  - Package Version: 0.60.0

Other Notes:
:: Building package: vte
:: Downloading http://ftp.gnome.org/pub/gnome/sources/vte/0.60/vte-0.60.0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  522k  100  522k    0     0  1094k      0 --:--:-- --:--:-- --:--:-- 1094k
:: Extacting vte-0.60.0.tar.xz to the sources directory
:: Compiling package
[...]

Found CMake: /usr/bin/cmake (3.16.5)
Run-time dependency libsystemd found: NO (tried pkgconfig and cmake)

meson.build:444:2: ERROR: Dependency "libsystemd" not found, tried pkgconfig and cmake

A full log can be found at /usr/ports/packages/vte/work/src/vte-0.60.0/build/meson-logs/meson-log.txt
:: Failed to compile package: vte

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/3b1e1130867bb3ace236b673aca8861d66f1aa53

**Comment by protonesso** [comment]
didn't know they added support for systemd

**Comment by robertwolter** [comment]
Ok, now it works.
BTW: will there be support for systemd at all?

**Comment by protonesso** [comment]
@robertwolter if consolekit will be very broken. I don't want systemd in ataraxia tbh, neither elogind
