### ISSUE TITLE
Compilation fails for xfce because dependency xfce4-notifyd ist not met, although it's installed

### ISSUE THREAD

**Issue by robertwolter** [ataraxialinux/ataraxia#110]
---
title: 'Bug Report xfce xfce4-notifyd'
labels: bug xfce xfce4-notifyd
  ---

# Package Bug: xfce xfce4-notifyd

## Expected Behavior
Compilation success

## Actual Behavior
Compilation fails

## Steps to Reproduce the Problem

  1.
neko emerge xfce
## Specifications

  - Architecture:  x64_86
  - Package Version: 4.14.0.20191029-1.x86_64

Other Notes:
neko emerge xfce

[...]

:: Building package: xfce
:: Compiling package
:: Removing junk from package
:: Removing libtool files
:: Removing locales
:: Removing documentation
:: Removing debug information from binary files
:: Compressing manual pages
:: Generating package
Building target platforms: x86_64
Building for target x86_64
warning: Could not canonicalize hostname: end-pc
Processing files: xfce-4.14.0.20191029-1.x86_64
Provides: xfce = 4.14.0.20191029-1
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /usr/ports/packages/xfce/work/pkg
Wrote: /root/rpmbuild/RPMS/x86_64/xfce-4.14.0.20191029-1.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.INlPkF
+ umask 022
+ cd /root/rpmbuild/BUILD
+ /bin/rm -rf /usr/ports/packages/xfce/work/pkg
+ RPM_EC=0 
+ jobs -p
+ exit 0
Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.JiPKAN
+ umask 022
+ cd /root/rpmbuild/BUILD
+ RPM_EC=0 
+ jobs -p
+ exit 0
:: Package was successfuly built
:: Checking package
:: Installing package: xfce
:: Checking for file conflicts
:: Extracting package
error: Failed dependencies:
	xfce4-notifyd is needed by xfce-4.14.0.20191029-1.x86_64
:: Failed to install package

# try re-installation of xfce4-notifyd
neko emerge xfce4-notifyd
:: Package have already built
:: Checking package
:: Updating package: xfce4-terminal
:: Extracting package
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:xfce4-terminal-0.8.9.1-1         ################################# [ 50%]
Cleaning up / removing...
   2:xfce4-terminal-0.8.9.1-1         ################################# [100%]
:: Package was successfully installed

# retry installation of xfce
neko emerge xfce
:: Package have already built
:: Checking package
:: Updating package: xfce4-terminal
:: Extracting package
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:xfce4-terminal-0.8.9.1-1         ################################# [ 50%]
Cleaning up / removing...
   2:xfce4-terminal-0.8.9.1-1         ################################# [100%]
:: Package was successfully installed
:: Package have already built
:: Checking package
:: Installing package: xfce
:: Checking for file conflicts
:: Extracting package
error: Failed dependencies:
	xfce4-notifyd is needed by xfce-4.14.0.20191029-1.x86_64
:: Failed to install package

**Comment by protonesso** [comment]
doh!

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/68bb89a5624841fc6c984dcd90ed4e4c7c6e9f60

**Comment by robertwolter** [comment]
Thanks, NOW xfce was installed completely.

**Comment by protonesso** [comment]
Nice!
