### ISSUE TITLE
neko upgrade: building package gcr fails

### ISSUE THREAD

**Issue by robertwolter** [ataraxialinux/ataraxia#112]
neko upgrade

[...]
:: Building package: gcr
:: Downloading http://ftp.gnome.org/pub/gnome/sources/gcr/3.36/gcr-3.36.0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1001k  100 1001k    0     0  1534k      0 --:--:-- --:--:-- --:--:-- 1531k
:: Extacting gcr-3.36.0.tar.xz to the sources directory
:: Compiling package
/usr/ports/packages/gcr/KagamiBuild: line 16: ./configure: No such file or directory
:: Failed to compile package: gcr
:: Failed to updated system

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/6cd39d32ea66735d260d571048b62b25ddcabd3c

**Comment by protonesso** [comment]
Don't have such time to test updates tbh

**Comment by ata-star** [comment]
downloaded the tarball, no configure

**Comment by robertwolter** [comment]
Still doesn't work:

neko upgrade
:: Checking for updates
grep: /KagamiBuild: No such file or directory
grep: /KagamiBuild: No such file or directory
:: Following packages will be updated
[UP] gcr [UP] glib [UP] gnome-online-accounts [UP] gsettings-desktop-schemas [UP] icu [UP] libsecret [UP] libuv [UP] libwpe [UP] mesa [UP] sdl2 [UP] vala [UP] webkitgtk [UP] wpebackend-fdo [UP] xorg-server 

:: Building package: gcr
:: Extacting gcr-3.36.0.tar.xz to the sources directory
:: Compiling package
The Meson build system
Version: 0.53.2
Source dir: /usr/ports/packages/gcr/work/src/gcr-3.36.0
Build dir: /usr/ports/packages/gcr/work/src/gcr-3.36.0/build
Build type: native build
Project name: gcr
Project version: 3.36.0
Appending CFLAGS from environment: '-g0 -Os -s -fexcess-precision=fast -fomit-frame-pointer -Wl,--as-needed -pipe'
Appending CFLAGS from environment: '-g0 -Os -s -fexcess-precision=fast -fomit-frame-pointer -Wl,--as-needed -pipe'
C compiler for the host machine: ccache gcc (gcc 9.3.0 "gcc (Ataraxia Linux edition 9.3.0 for x86_64) 9.3.0")
C linker for the host machine: gcc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency glib-2.0 found: YES 2.64.0
Run-time dependency gmodule-no-export-2.0 found: YES 2.64.0
Run-time dependency gthread-2.0 found: YES 2.64.0
Run-time dependency gobject-2.0 found: YES 2.64.0
Run-time dependency gio-2.0 found: YES 2.64.0
Run-time dependency gio-unix-2.0 found: YES 2.64.0
Program gpg2 found: YES (/usr/bin/gpg2)
Run-time dependency libgcrypt found: YES 1.8.5
Run-time dependency p11-kit-1 found: YES 0.23.20
Run-time dependency gtk+-3.0 found: YES 3.24.14
Run-time dependency gtk+-x11-3.0 found: YES 3.24.14
Has header "locale.h" : YES 
Checking for function "timegm" : YES 
Checking for function "mlock" : YES 
Configuring config.h using configuration
Configuring gck-version.h using configuration
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Compiler for C supports link arguments -Wl,--version-script,/usr/ports/packages/gcr/work/src/gcr-3.36.0/gck/libgck.map: YES 
Configuring gcr-version.h using configuration
Program gcr-mkoids found: YES (/bin/sh /usr/ports/packages/gcr/work/src/gcr-3.36.0/gcr/gcr-mkoids)
Compiler for C supports link arguments -Wl,--version-script,/usr/ports/packages/gcr/work/src/gcr-3.36.0/gcr/libgcr-base.map: YES 
Configuring org.gnome.keyring.SystemPrompter.service using configuration
Configuring org.gnome.keyring.PrivatePrompter.service using configuration
Compiler for C supports link arguments -Wl,--version-script,/usr/ports/packages/gcr/work/src/gcr-3.36.0/ui/libgcr-ui.map: YES 
WARNING: Already generated a pkg-config file for gcr-ui-3
Configuring gcr-viewer.desktop.in using configuration
Configuring gcr-prompter.desktop.in using configuration
Configuring version.xml using configuration

docs/reference/gck/meson.build:19:6: ERROR: Program(s) ['gtkdoc-scan'] not found or not executable

A full log can be found at /usr/ports/packages/gcr/work/src/gcr-3.36.0/build/meson-logs/meson-log.txt
:: Failed to compile package: gcr
:: Failed to updated system

**Comment by ata-star** [comment]
docs/reference/gck/meson.build:19:6: ERROR: Program(s) ['gtkdoc-scan'] not found or not executable

Missing deb?

**Comment by protonesso** [comment]
I will fix that we I come home

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/078b61c3db70a7da01612f76ba176dd71a1fcb83

**Comment by protonesso** [comment]
gcr doesn't fail anymore
