### ISSUE TITLE
startxfce4 -> system hangs

### ISSUE THREAD

**Issue by robertwolter** [ataraxialinux/ataraxia#114]
After logging in as normal user:
startxfce4
-> system hangs completely, keyboard and mouse don't work, can't switch to tty, mouse pointer doesn't move.
![Ataraxia-Linux-startxfce4](https://user-images.githubusercontent.com/18753171/76575079-15c0be00-64b6-11ea-985c-910053849bce.png)

**Comment by protonesso** [comment]
check if you user in `input` group

**Comment by robertwolter** [comment]
Yes:
grep input /etc/group
input:x:97:ata

**Comment by protonesso** [comment]
which x11 input driver you have installed?

2020年3月13日(金) 16:55 Robert <notifications@github.com>:

**Comment by protonesso** [comment]
libinput-list-devices and it's output

2020年3月13日(金) 16:57 Nagakamira <nagakamira@gmail.com>:

**Comment by robertwolter** [comment]
```
libinput-list-devices
bash: libinput-list-devices: command not found
```

To which package does it belong?

**Comment by protonesso** [comment]
I think you haven't installed input driver! Install xf86-input-libinput

**Comment by robertwolter** [comment]
It was not in the PATH but now I found it
/usr/lib/libinput/libinput-list-devices

**Comment by protonesso** [comment]
Also check xorg log and send it here

**Comment by robertwolter** [comment]
Ok, problem solved. I installed lightdm-gtk-greeter which was still missing after installing lightdm. I added lightdm to the default runlevel and it works now. I can successfully login.
