### ISSUE TITLE
Cannot build mupdf.

### ISSUE THREAD

**Issue by ghost** [ataraxialinux/ataraxia#126]
Output :
```
source/fitz/font.c:6:10: fatal error: ft2build.h: No such file or directory
    6 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:101: build/release/source/fitz/font.o] Error 1
```
freetype package has been installed.

**Comment by protonesso** [comment]
can you try it https://github.com/ataraxialinux/ataraxia/commit/5237756679e26ad360668ae36bae3f38f377187c

**Comment by ghost** [comment]
> can you try it [5237756](https://github.com/ataraxialinux/ataraxia/commit/5237756679e26ad360668ae36bae3f38f377187c)

A different error message appeared.
```
source/fitz/filter-jbig2.c:242:10: fatal error: jbig2.h: No such file or directory
  242 | #include <jbig2.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:101: build/release/source/fitz/filter-jbig2.o] Error 1
```

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/63509abffcabfd37e748a3cfadaa0eab0ebd492e

**Comment by protonesso** [comment]
@ixavoz try this maybe helps

**Comment by ghost** [comment]
> @ixavoz try this maybe helps

Sorry for the late reply.
```
/usr/bin/ld: build/release/libmupdf-pkcs7.a(pkcs7-openssl.o): in function `add_from_bags':
pkcs7-openssl.c:(.text.add_from_bags+0xba): undefined reference to `PKCS12_SAFEBAG_get0_p8inf'
/usr/bin/ld: pkcs7-openssl.c:(.text.add_from_bags+0xdd): undefined reference to `PKCS12_SAFEBAG_get0_safes'
collect2: error: ld returned 1 exit status
make: *** [Makefile:216: build/release/mutool] Error 1
```

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/662c134d9cdcdfa8825ab379e66ae0c3f1768e1c

**Comment by ixavoz** [comment]
It is working now.

**Comment by ghost** [comment]
I get segementation fault error when running the program.

**Comment by protonesso** [comment]
@ixavoz hmm, works for me
![Screenshot from 2020-04-07 14-30-50](https://user-images.githubusercontent.com/47295761/78681741-a4b9ce00-78dc-11ea-9782-3bbbe7c01f25.png)

**Comment by protonesso** [comment]
perhaps you're using pdf file which cannot be read by mupdf? Or you can try linux-nonsec (Linux kernel without security features)

**Comment by ghost** [comment]
It is working now.
