### ISSUE TITLE
Cannot build sane.

### ISSUE THREAD

**Issue by ghost** [ataraxialinux/ataraxia#134]
Output :
```
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force -I m4
fatal: not a git repository (or any of the parent directories): .git
configure.ac:14: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:14: the top level
autom4te: m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```

**Comment by protonesso** [comment]
"what happens when you don't test packages"

2020年4月2日(木) 7:29 ixavoz <notifications@github.com>:

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/662c134d9cdcdfa8825ab379e66ae0c3f1768e1c

**Comment by ghost** [comment]
> [662c134](https://github.com/ataraxialinux/ataraxia/commit/662c134d9cdcdfa8825ab379e66ae0c3f1768e1c)

I can build it now but somehow there is /var/lock file conflicted with base-files package.

**Comment by protonesso** [comment]
https://github.com/ataraxialinux/ataraxia/commit/030031f74b260216ea6de7b3b70d1c1506ac0812

**Comment by protonesso** [comment]
Rebuild the package

**Comment by ghost** [comment]
It is working now.
