### ISSUE TITLE
From base system Snapshot on March 10, 2020 neko up problem

### ISSUE THREAD

**Issue by aicsx** [ataraxialinux/ataraxia#135]
---
title: 'Report'
  --- 
  1. # neko up return error:
you can view it "utf" enable ... http://termbin.com/b43k ... 
file /var/mail from install of base-files-0.9-1-x86_64 conflicts with files from package base-files-0.5-1-x86_64
:: failed to update system   

Other Notes: please, i search freenode chan for speak directly but I didn't find anything or anyone.

**Comment by protonesso** [comment]
neko em -f base-files

**Comment by aicsx** [comment]
ok, thank you. It's work. 
do you have an official irc channel to discuss?

**Comment by protonesso** [comment]
I think irc channel is dead. Nobody uses it. But you can use matrix,
discord and telegram

2020年4月4日(土) 14:49 ax <notifications@github.com>:

**Comment by protonesso** [comment]
@aicsx problem is fixed, right?

**Comment by aicsx** [comment]
Yes Man, my problem fixed, i'm testing your project, It Is awesome. Now i'm compiling xorg and other. 
one thing is not clear to me ... neko uses RPM packages?  in the sense can also reason in binary way with install without compilation?

**Comment by protonesso** [comment]
there's outdated repo and I'm working on libsolv

**Comment by aicsx** [comment]
ok now it's clear. Last thing then leaves you alone: P My upgrade was successful
However, I point out that neko up always returns grep: / KagamiBuild no such file or directory
Also / etc / ataraxia-release is no longer linked to / etc / os-release ... maybe a post update would be needed. 
For now you can close this issue. Thank you bro!

**Comment by protonesso** [comment]
Hmm, will check that grep problem

**Comment by protonesso** [comment]
#ataraxialinux on irc.freenode.net

**Comment by aicsx** [comment]
It awesome :) im joining. dispassionate advice: why #ataraxialinux and not #ataraxia?  all distributions on irc are beyond the linux suffix, it is easier for Shell textual client to refer to the name .. but It only my point of view Il 6 apr 2020 12:52, Ishimoto Shinobu <notifications@github.com> ha scritto:
#ataraxialinux on irc.freenode.net
