### ISSUE TITLE
SELinux enforcing mode, can't login

### ISSUE THREAD

**Issue by protonesso** [ataraxialinux/ataraxia#175]
## Expected Behavior
Working login system

## Actual Behavior
prints: ```
cannot make/remove an entry for the specified session``` and other stuff

## Steps to Reproduce the Problem
 1. Use latest selinux-policy package
 2. Set selinux mode to enforcing in /etc/selinux/config
 3. Reboot

## Specifications

  - Architecture: all
  - Package Version:

## Notes:
Login system work with permissive mode with any policy
## QnA:
Q: Why does Ataraxia use SELinux?
A: Ataraxia tries to offer better security
Q: Can be SELinux removed?
A: no

**Comment by AwlsomeAlex** [comment]
Just get rid of Selinux. Simple. :bigbrain:

**Comment by protonesso** [comment]
fixed in this https://github.com/ataraxialinux/ataraxia/commit/8561af97b7a76bc11961b59dd2cc4c8490cec1a2
but no protection for pam
