### ISSUE TITLE
"Featured" snapshot with working GUI?

### ISSUE THREAD

**Issue by rubyFeedback** [ataraxialinux/ataraxia#177]
I just read about ataraxia on reddit. It looks very interesting.

I download the snapshot here:

https://github.com/ataraxialinux/ataraxia/releases/download/200705/ataraxialinux-x86_64.iso

Noticed it was only 51MB. I assume it does not come with xorg or wayland and stuff.

I tend to need them though, also a browser. Is there a possibility to provide a slightly
larger snapshot? Not asking for something that may be massive, mind you, but 
I would not mind something like icewm + xorg mostly as I find this to be more convenient
to work with.

**Comment by protonesso** [comment]
This is livecd to installer image, like Gentoo or arch, you can use snapshot from May 3rd
