### ISSUE TITLE
Minor English changes to the installation page

### ISSUE THREAD

**Issue by ghost** [ataraxialinux/ataraxia#180]
I have done some minor English improvements to the installation page, couldn't find a way to PR the wiki page though so it would be appreciated if I can get some help on it!

Contents of the changed page: [here](http://ix.io/2s4f)

**Comment by protonesso** [comment]
Thank you!

**Comment by protonesso** [comment]
merged https://github.com/ataraxialinux/ataraxia/wiki/Installation/_compare/e119235c6e590cc741fb7ec270771ee81801b8a5...33e8f2a80c1ae7ba88f9f169f3f1a6a339497e66
