### ISSUE TITLE
Package 'highlight' has wrong URL

### ISSUE THREAD

**Issue by awilfox** [ataraxialinux/ataraxia#185]
---
title: 'Package highlight has wrong URL'
labels: bug
  ---

# Package Bug: highlight

## Expected Behavior
URL should be `http://www.andre-simon.de/doku/highlight/highlight.php` or similar

## Actual Behavior
URL is for GNU M4.

## Specifications

  - Architecture: ppc64
  - Package Version: 3.57.1

Other Notes:
Came across this while looking for the proper URL for the 3.57.1 source code (it is ZIP now!), not running Ataraxia on my machine.

**Comment by protonesso** [comment]
Thank you!
