### ISSUE TITLE
Error compiling on every attempted build

### ISSUE THREAD

**Issue by ghost** [ataraxialinux/ataraxia#214]
---
title: ''
labels: bug
  ---

# Package Bug: Build script

## Expected Behavior
Compiling just fine

## Actual Behavior
![image](https://user-images.githubusercontent.com/25110919/98716729-1027ba80-235a-11eb-84fe-36e2b51623bf.png)
There is always an error when compiling something, here's one for compiling for aarch64.

## Steps to Reproduce the Problem

  1. ./build stage -j12 -a aarch64 meta-toolchain
  2. ./build image -j12 -a aarch64 -d mate

## Specifications

  - Architecture: aarch64 target

Build machine specs:

![image](https://user-images.githubusercontent.com/25110919/98717012-7a405f80-235a-11eb-9409-b3b83b808a95.png)

Other Notes:

I have followed the guide to building from source.

**Comment by protonesso** [comment]
I guess you don't have zlib headers installed

**Comment by protonesso** [comment]
Also building with desktop environment is not supported yet

**Comment by protonesso** [comment]
I will investigate, I haven't tried to build it on arch (I'm building it on Ataraxia, Debian and Fedora)
