### ISSUE TITLE
Relicense vis, lua-lpeg

### ISSUE THREAD

**Issue by bmoneill** [ataraxialinux/ataraxia#235]
---
title: 'Relicense vis, lua-lpeg packages to GPLv3'
labels: bug
  ---

# Packages: lua-lpeg, vis

As maintainer, the build scripts for the packages listed above should be relicensed under the GNU GPLv3 license.

**Comment by protonesso** [comment]
fixed in this https://github.com/ataraxialinux/ataraxia/commit/9020c130d6363cf926c0d59cf1caa3988b3dc4ab
