### ISSUE TITLE
No Networking on Virtualbox

### ISSUE THREAD

**Issue by AwlsomeAlex** [ataraxialinux/ataraxia#29]
I'm currently testing JanusLinux on Virtualbox 5.2.18 r124319 (macOS High Sierra Host) and I can't get networking to work on BETA 5 release of JanusLinux. I have followed the guide by modifying `/etc/network/interfaces` by adding `iface enp0s3 inet dhcp` with `enp0s3` being found by typing `ifconfig -a | less`. I tried all the Intel Pro Adapter Types and the PCnet ones don't even show up at all. What should I do?

**Comment by ghost** [comment]
1. You use snapshots?
2. itconfig -a and select YOUR interface

**Comment by ghost** [comment]
Don't forget to run ifup -a
