### ISSUE TITLE
Comparison to Sabotage Linux

### ISSUE THREAD

**Issue by pltrz** [ataraxialinux/ataraxia#43]
First off, congrats and hats off for releasing the first tech preview. It is a lot of work you've put in. I've only been watching the project for a couple of weeks but it looks very interesting to me.

So my questions revolve around what are the differences and similarities between Janus Linux and [Sabotage Linux](https://github.com/sabotage-linux/sabotage)?

- What are the differences in goals/vision between Janus and Sabotage?
- What are the differences in utilities that will be used? For example Sabotage uses runit, which I like and prefer over OpenRC?
- Anything else worth knowing?

**Comment by nee-san** [comment]
So I use runit too, but sabotage uses busybox's runit. Also runit used by void Linux and many other distros. Also I use GNU userland (planning to switch on sbase and ubase). Also januslinux can be cross compiled like buildroot or T2 (no chroot toolchain at all, then no build-stage0). januslinux is up to date than sabotage (I update packages when they appear). And januslinux has more build deps to make it a bit extended. Code base is different from sabotage (you can compare them).

**Comment by nee-san** [comment]
So that's all :)

**Comment by nee-san** [comment]
Also I need to add documentation about installation process

**Comment by pltrz** [comment]
Cool, thanks for the info! I'll be sure to try it out once the installation is documented.

**Comment by nee-san** [comment]
@pltrz so i added install docs. install it in qemu
