### ISSUE TITLE
./build: line 49: pkgmk: command not found

### ISSUE THREAD

**Issue by scsijon** [ataraxialinux/ataraxia#58]
---
title: 'Bug Report'
labels: bug
  ---

# Package Bug: MISSING OUTDATED PACKAGE

## Actual Behavior
# BARCH=x86_64 ./build stage 0
==> Setting up the build environment
==> Building the build environment
==> Building cross-toolchain for 'x86_64' platform
==> Adding fake ldconfig
==> Emerging 'base-files' package
./build: line 49: pkgmk: command not found

## Steps to Reproduce the Problem

  1. see above

## Specifications

  - Architecture: x86_64
  - Package Version:20190520

Other Notes:
1-It looked like a distribution worth trying, but if it's not buildable from other versions of linux it's not. I also note nothing in the prerequisite list that includes a generic package for the pkgmk set.

**Comment by scsijon** [comment]
I eventually tracked down the github pkgutils repository on crux.nu, but can't find a version that actually installs and works generically.

**Comment by protonesso** [comment]
compile this pkgtools: https://github.com/protonesso/pkgutils
```
make -f Makefile.dynamic
make install
```

**Comment by protonesso** [comment]
Docs updated

**Comment by scsijon** [comment]
Magic, built that one, others tried failed. Added to the Puppy Linux system utilities available, http://www.murga-linux.com/puppy/viewtopic.php?t=116180 relates. 
And now on to problems.... :-())))}
