### ISSUE TITLE
missing clean in ./build

### ISSUE THREAD

**Issue by scsijon** [ataraxialinux/ataraxia#61]
---
title: 'Enhancement'
labels: enhancement
  ---

# Package Bug: ./build

## Expected Behavior
reinitialize packahe to basic settings and filesset

## Actual Behavior
nothing happens

## Steps to Reproduce the Problem

  1. ./build clean

Other Notes:

Sort of expected nowadays, rather than blowing away everything and reopening/downloading and reinstalling. Sort of like the make clean subcommand.

**Comment by protonesso** [comment]
It can clean everything automatically
