### ISSUE TITLE
Just this.

### ISSUE THREAD

**Issue by TheOrangeCat** [ataraxialinux/ataraxia#66]
@protonesso 
=======> Downloading 'http://download.oracle.com/berkeley-db/db-6.2.38.tar.gz'.
=======> Partial download found, trying to resume
--2019-06-28 22:40:47--  http://download.oracle.com/berkeley-db/db-6.2.38.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.52.185.13
Connecting to download.oracle.com (download.oracle.com)|23.52.185.13|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.oracle.com/berkeley-db/db-6.2.38.tar.gz [following]
--2019-06-28 22:40:54--  https://download.oracle.com/berkeley-db/db-6.2.38.tar.gz
Connecting to download.oracle.com (download.oracle.com)|23.52.185.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-06-28 22:40:55 ERROR 404: Not Found.

=======> Partial download failed, restarting
--2019-06-28 22:40:55--  http://download.oracle.com/berkeley-db/db-6.2.38.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.52.185.13
Connecting to download.oracle.com (download.oracle.com)|23.52.185.13|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.oracle.com/berkeley-db/db-6.2.38.tar.gz [following]
--2019-06-28 22:40:59--  https://download.oracle.com/berkeley-db/db-6.2.38.tar.gz
Connecting to download.oracle.com (download.oracle.com)|23.52.185.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-06-28 22:41:00 ERROR 404: Not Found.

=======> ERROR: Downloading 'http://download.oracle.com/berkeley-db/db-6.2.38.tar.gz' failed.

**Comment by protonesso** [comment]
Will fix when internet will work

**Comment by protonesso** [comment]
fixed in https://github.com/ataraxialinux/ataraxia/tree/switch-to-kagami-and-maybe-s6/packages/db

**Comment by TheOrangeCat** [comment]
Do you even check this?
```
 >>> Setting up the build environment
 >>> Preparing the environment for build
 >>> Building cross-toolchain for 'x86_64' platform
 >>> Adding fake ldconfig
 >>> Building package: 'base-files'
 * Compiling package
 * Removing junk from package
 * Removing locales
 * Removing documentation
 * Compressing manual pages
 * Generating package metadata
 * Creating package archive
 >>> Package have been successfully built
 >>> Installing package: 'base-files'
 * Checking for file conflicts
 * Saving files
 * Extracting package
 * Restoring files
 * Doing package registration
 >>> Package was successfully installed
 >>> Building package: 'host-file'
 * Downloading ftp://ftp.astron.com/pub/file/file-5.37.tar.gz
-=O=-               #    #     #     #                                         
curl: (6) Could not resolve host: ftp.astron.com
 * Downloading 'ftp://ftp.astron.com/pub/file/file-5.37.tar.gz' failed.
```
