### ISSUE TITLE
Build system not working

### ISSUE THREAD

**Issue by TheOrangeCat** [ataraxialinux/ataraxia#70]
---
title: 'Bug Report'
labels: bug
  ---

# Package Bug: Build system not working

## Expected Behavior
Begin building

## Actual Behavior
Nothing

## Steps to Reproduce the Problem
  1.```git clone``` the ataraxialinux/ataraxia repo
  2. Execute ```BARCH=x86_64  ./build stage 1```

## Specifications

  - Host architecture: x86_64
  - Build architecture: x86_64

Other Notes:
Every option except ```./build``` returns nothing.

**Comment by protonesso** [comment]
./build -s 1 -a x86_64

**Comment by TheOrangeCat** [comment]
Then update the docs.

**Comment by TheOrangeCat** [comment]
Also, how do you install kagami if there's no docs or references?
This is worse than kot-pkg.

**Comment by protonesso** [comment]
>This is worse than kot-pkg.
tfw your package manager is not self-hosting

**Comment by TheOrangeCat** [comment]
At least all documentation for kot-pkg is correct

**Comment by TheOrangeCat** [comment]
Plus the docs still don't document the options.

**Comment by protonesso** [comment]
kagami also have good documentation
