### ISSUE TITLE
Add nodejs too, not just php :-)

### ISSUE THREAD

**Issue by ghost** [ataraxialinux/ataraxia#85]

**Comment by protonesso** [comment]
Nodejs is already in repository: https://github.com/ataraxialinux/ataraxia/blob/master/packages/nodejs/KagamiBuild

To install it: ne -E nodejs

**Comment by ghost** [comment]
@protonesso You just did not write it on the roadmap then. https://github.com/ataraxialinux/ataraxia/blob/master/docs/roadmap.md
